### PR TITLE
English Support added

### PR DESCRIPTION
**Pull request by SHOCKWAVE07**

### CODE REVIEW

**Comment by SHOCKWAVE07** [comment]
Added English Support for better reach.

**Review by bluczko — CHANGES_REQUESTED** [review]
Hello! I'm glad that You find this code useful! I very much appreciate Your contribution, however I would like to ask You to make some adjustments before I can accept Your changes:
1. Remove all `*.pyc` files, as they are specific to Your local environment. An appropriate entry to `.gitignore` would be a nice touch.
2. There are two untranslated strings in `launch.pyw` file - please modify them aswell.
3. Restore dependency versions in `requirements.txt`. It would be a good practice to replace the qualifiers from hard `==` to more liberal `>=`, as it provides a hint about dependency versions that made this code run properly.

I'll be happy to accept Your PR when these issues are resolved.

**Comment by SHOCKWAVE07** [comment]
Thanks for acknowledgement, I'll do it as mentioned and I have also
converted Python 2 code to Python 3.

**Comment by SHOCKWAVE07** [comment]
I have made the changes as follows
1. *.pyc in .gitignore.
2. Translated remaining words in .pyw file.
3. Tried >= version but had too many version conflicts so used hard instead.

Also included 'gurobipy' in requirements.txt to have at least 1 solver installed.

**Review by bluczko — CHANGES_REQUESTED** [review]
I can still see some .pyc files in `ui/__pycache__/` directory.

I'm not sure what happened to the `requirements.txt` file though, because You added a lot of libraries that shouldn't belong here - please remove them. If deprecated or incompatible packages are an issue, then leave them bumped to the latest minor version (i.e.: `numpy==1.26.4`).

I would appreciate if You would remove Gurobi dependencies and replace it with free and open-source `glpk` package. Gurobi is a proprietary, paid solver that requires a lot of work to make it run, so I wouldn't want to suggest it as a first choice.

**Comment by SHOCKWAVE07** [comment]
I used pip freeze to list all packages into requirements.txt before but I have fixed it. 

Removed Gurobi and ui/__pycache__/ as mentioned.

**Review by bluczko — APPROVED** [review]
Looks great, thank You for contributing!

**Pull request merged**
